server:
  port: 8086
spring:
  application:
    name: productos-service
  datasource:
    url: jdbc:postgresql://ep-withered-king-aa21vv8q-pooler.westus3.azure.neon.tech:5432/neondb?user=neondb_owner&password=npg_0gnbkuv5IWlH&sslmode=require
    username: neondb_owner
    password: npg_0gnbkuv5IWlH
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    enabled: false
  properties:
    hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    discovery:
      enabled: true
    loadbalancer:
      retry:
        enabled: true

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.tienda.productos: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    level: "%5p [${spring.application.name}, %X{traceId:-},%X{spanId:-}]"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: "${spring.application.name}:${spring.application.instance_id:${random.value}}"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

# Tracing
management:
  tracing:
        sampling:
            probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,*
  endpoint:
    health:
      show-details: always