apiVersion: v1
kind: Service
metadata:
  name: productos-service
spec:
  selector:
    app: productos-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30081
  type:  NodePort